/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAvatarModule = new ScriptModule("Avatar");
			EntityDef.moduledefs["Avatar"] = pAvatarModule;
			EntityDef.idmoduledefs[1] = pAvatarModule;

			Property pAvatar_position = new Property();
			pAvatar_position.name = "position";
			pAvatar_position.properUtype = 40000;
			pAvatar_position.properFlags = 4;
			pAvatar_position.aliasID = 1;
			Vector3 Avatar_position_defval = new Vector3();
			pAvatar_position.defaultVal = Avatar_position_defval;
			pAvatarModule.propertys["position"] = pAvatar_position; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_position.aliasID] = pAvatar_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(position / 40000).");

			Property pAvatar_direction = new Property();
			pAvatar_direction.name = "direction";
			pAvatar_direction.properUtype = 40001;
			pAvatar_direction.properFlags = 4;
			pAvatar_direction.aliasID = 2;
			Vector3 Avatar_direction_defval = new Vector3();
			pAvatar_direction.defaultVal = Avatar_direction_defval;
			pAvatarModule.propertys["direction"] = pAvatar_direction; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_direction.aliasID] = pAvatar_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(direction / 40001).");

			Property pAvatar_spaceID = new Property();
			pAvatar_spaceID.name = "spaceID";
			pAvatar_spaceID.properUtype = 40002;
			pAvatar_spaceID.properFlags = 16;
			pAvatar_spaceID.aliasID = 3;
			UInt32 Avatar_spaceID_defval;
			UInt32.TryParse("", out Avatar_spaceID_defval);
			pAvatar_spaceID.defaultVal = Avatar_spaceID_defval;
			pAvatarModule.propertys["spaceID"] = pAvatar_spaceID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceID.aliasID] = pAvatar_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceID / 40002).");

			Property pAvatar_nameS = new Property();
			pAvatar_nameS.name = "nameS";
			pAvatar_nameS.properUtype = 4;
			pAvatar_nameS.properFlags = 4;
			pAvatar_nameS.aliasID = 4;
			string Avatar_nameS_defval = "";
			pAvatar_nameS.defaultVal = Avatar_nameS_defval;
			pAvatarModule.propertys["nameS"] = pAvatar_nameS; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_nameS.aliasID] = pAvatar_nameS;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(nameS / 4).");

			Property pAvatar_progress = new Property();
			pAvatar_progress.name = "progress";
			pAvatar_progress.properUtype = 6;
			pAvatar_progress.properFlags = 128;
			pAvatar_progress.aliasID = 5;
			Int32 Avatar_progress_defval;
			Int32.TryParse("0", out Avatar_progress_defval);
			pAvatar_progress.defaultVal = Avatar_progress_defval;
			pAvatarModule.propertys["progress"] = pAvatar_progress; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_progress.aliasID] = pAvatar_progress;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(progress / 6).");

			Property pAvatar_roomNo = new Property();
			pAvatar_roomNo.name = "roomNo";
			pAvatar_roomNo.properUtype = 8;
			pAvatar_roomNo.properFlags = 4;
			pAvatar_roomNo.aliasID = 6;
			Int32 Avatar_roomNo_defval;
			Int32.TryParse("0", out Avatar_roomNo_defval);
			pAvatar_roomNo.defaultVal = Avatar_roomNo_defval;
			pAvatarModule.propertys["roomNo"] = pAvatar_roomNo; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_roomNo.aliasID] = pAvatar_roomNo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(roomNo / 8).");

			List<DATATYPE_BASE> pAvatar_onExitRoom_args = new List<DATATYPE_BASE>();
			pAvatar_onExitRoom_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onExitRoom = new Method();
			pAvatar_onExitRoom.name = "onExitRoom";
			pAvatar_onExitRoom.methodUtype = 22;
			pAvatar_onExitRoom.aliasID = 1;
			pAvatar_onExitRoom.args = pAvatar_onExitRoom_args;

			pAvatarModule.methods["onExitRoom"] = pAvatar_onExitRoom; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onExitRoom.aliasID] = pAvatar_onExitRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onExitRoom / 22).");

			List<DATATYPE_BASE> pAvatar_onGetProps_args = new List<DATATYPE_BASE>();
			pAvatar_onGetProps_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onGetProps = new Method();
			pAvatar_onGetProps.name = "onGetProps";
			pAvatar_onGetProps.methodUtype = 17;
			pAvatar_onGetProps.aliasID = 2;
			pAvatar_onGetProps.args = pAvatar_onGetProps_args;

			pAvatarModule.methods["onGetProps"] = pAvatar_onGetProps; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onGetProps.aliasID] = pAvatar_onGetProps;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onGetProps / 17).");

			List<DATATYPE_BASE> pAvatar_onLoadingFinish_args = new List<DATATYPE_BASE>();
			pAvatar_onLoadingFinish_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onLoadingFinish = new Method();
			pAvatar_onLoadingFinish.name = "onLoadingFinish";
			pAvatar_onLoadingFinish.methodUtype = 16;
			pAvatar_onLoadingFinish.aliasID = 3;
			pAvatar_onLoadingFinish.args = pAvatar_onLoadingFinish_args;

			pAvatarModule.methods["onLoadingFinish"] = pAvatar_onLoadingFinish; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onLoadingFinish.aliasID] = pAvatar_onLoadingFinish;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onLoadingFinish / 16).");

			List<DATATYPE_BASE> pAvatar_onLoginState_args = new List<DATATYPE_BASE>();
			pAvatar_onLoginState_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onLoginState = new Method();
			pAvatar_onLoginState.name = "onLoginState";
			pAvatar_onLoginState.methodUtype = 13;
			pAvatar_onLoginState.aliasID = 4;
			pAvatar_onLoginState.args = pAvatar_onLoginState_args;

			pAvatarModule.methods["onLoginState"] = pAvatar_onLoginState; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onLoginState.aliasID] = pAvatar_onLoginState;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onLoginState / 13).");

			List<DATATYPE_BASE> pAvatar_onMapModeChanged_args = new List<DATATYPE_BASE>();
			pAvatar_onMapModeChanged_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onMapModeChanged = new Method();
			pAvatar_onMapModeChanged.name = "onMapModeChanged";
			pAvatar_onMapModeChanged.methodUtype = 14;
			pAvatar_onMapModeChanged.aliasID = 5;
			pAvatar_onMapModeChanged.args = pAvatar_onMapModeChanged_args;

			pAvatarModule.methods["onMapModeChanged"] = pAvatar_onMapModeChanged; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onMapModeChanged.aliasID] = pAvatar_onMapModeChanged;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onMapModeChanged / 14).");

			List<DATATYPE_BASE> pAvatar_onMatchingFinish_args = new List<DATATYPE_BASE>();
			pAvatar_onMatchingFinish_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onMatchingFinish = new Method();
			pAvatar_onMatchingFinish.name = "onMatchingFinish";
			pAvatar_onMatchingFinish.methodUtype = 15;
			pAvatar_onMatchingFinish.aliasID = 6;
			pAvatar_onMatchingFinish.args = pAvatar_onMatchingFinish_args;

			pAvatarModule.methods["onMatchingFinish"] = pAvatar_onMatchingFinish; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onMatchingFinish.aliasID] = pAvatar_onMatchingFinish;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onMatchingFinish / 15).");

			List<DATATYPE_BASE> pAvatar_onReachDestination_args = new List<DATATYPE_BASE>();
			pAvatar_onReachDestination_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_onReachDestination_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onReachDestination = new Method();
			pAvatar_onReachDestination.name = "onReachDestination";
			pAvatar_onReachDestination.methodUtype = 20;
			pAvatar_onReachDestination.aliasID = 7;
			pAvatar_onReachDestination.args = pAvatar_onReachDestination_args;

			pAvatarModule.methods["onReachDestination"] = pAvatar_onReachDestination; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onReachDestination.aliasID] = pAvatar_onReachDestination;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onReachDestination / 20).");

			List<DATATYPE_BASE> pAvatar_onSkillResult_args = new List<DATATYPE_BASE>();
			pAvatar_onSkillResult_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_onSkillResult_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_onSkillResult_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onSkillResult = new Method();
			pAvatar_onSkillResult.name = "onSkillResult";
			pAvatar_onSkillResult.methodUtype = 19;
			pAvatar_onSkillResult.aliasID = 8;
			pAvatar_onSkillResult.args = pAvatar_onSkillResult_args;

			pAvatarModule.methods["onSkillResult"] = pAvatar_onSkillResult; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onSkillResult.aliasID] = pAvatar_onSkillResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onSkillResult / 19).");

			List<DATATYPE_BASE> pAvatar_onTimerChanged_args = new List<DATATYPE_BASE>();
			pAvatar_onTimerChanged_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onTimerChanged = new Method();
			pAvatar_onTimerChanged.name = "onTimerChanged";
			pAvatar_onTimerChanged.methodUtype = 21;
			pAvatar_onTimerChanged.aliasID = 9;
			pAvatar_onTimerChanged.args = pAvatar_onTimerChanged_args;

			pAvatarModule.methods["onTimerChanged"] = pAvatar_onTimerChanged; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onTimerChanged.aliasID] = pAvatar_onTimerChanged;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onTimerChanged / 21).");

			List<DATATYPE_BASE> pAvatar_onUseSkill_args = new List<DATATYPE_BASE>();
			pAvatar_onUseSkill_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_onUseSkill_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_onUseSkill_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onUseSkill = new Method();
			pAvatar_onUseSkill.name = "onUseSkill";
			pAvatar_onUseSkill.methodUtype = 18;
			pAvatar_onUseSkill.aliasID = 10;
			pAvatar_onUseSkill.args = pAvatar_onUseSkill_args;

			pAvatarModule.methods["onUseSkill"] = pAvatar_onUseSkill; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onUseSkill.aliasID] = pAvatar_onUseSkill;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onUseSkill / 18).");

			List<DATATYPE_BASE> pAvatar_regStartMatching_args = new List<DATATYPE_BASE>();
			pAvatar_regStartMatching_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_regStartMatching_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_regStartMatching_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_regStartMatching = new Method();
			pAvatar_regStartMatching.name = "regStartMatching";
			pAvatar_regStartMatching.methodUtype = 6;
			pAvatar_regStartMatching.aliasID = -1;
			pAvatar_regStartMatching.args = pAvatar_regStartMatching_args;

			pAvatarModule.methods["regStartMatching"] = pAvatar_regStartMatching; 
			pAvatarModule.base_methods["regStartMatching"] = pAvatar_regStartMatching;

			pAvatarModule.idbase_methods[pAvatar_regStartMatching.methodUtype] = pAvatar_regStartMatching;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(regStartMatching / 6).");

			List<DATATYPE_BASE> pAvatar_regGetProps_args = new List<DATATYPE_BASE>();
			pAvatar_regGetProps_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_regGetProps = new Method();
			pAvatar_regGetProps.name = "regGetProps";
			pAvatar_regGetProps.methodUtype = 3;
			pAvatar_regGetProps.aliasID = -1;
			pAvatar_regGetProps.args = pAvatar_regGetProps_args;

			pAvatarModule.methods["regGetProps"] = pAvatar_regGetProps; 
			pAvatarModule.cell_methods["regGetProps"] = pAvatar_regGetProps;

			pAvatarModule.idcell_methods[pAvatar_regGetProps.methodUtype] = pAvatar_regGetProps;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(regGetProps / 3).");

			List<DATATYPE_BASE> pAvatar_regProgress_args = new List<DATATYPE_BASE>();
			pAvatar_regProgress_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_regProgress = new Method();
			pAvatar_regProgress.name = "regProgress";
			pAvatar_regProgress.methodUtype = 1;
			pAvatar_regProgress.aliasID = -1;
			pAvatar_regProgress.args = pAvatar_regProgress_args;

			pAvatarModule.methods["regProgress"] = pAvatar_regProgress; 
			pAvatarModule.cell_methods["regProgress"] = pAvatar_regProgress;

			pAvatarModule.idcell_methods[pAvatar_regProgress.methodUtype] = pAvatar_regProgress;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(regProgress / 1).");

			List<DATATYPE_BASE> pAvatar_regReachDestination_args = new List<DATATYPE_BASE>();

			Method pAvatar_regReachDestination = new Method();
			pAvatar_regReachDestination.name = "regReachDestination";
			pAvatar_regReachDestination.methodUtype = 2;
			pAvatar_regReachDestination.aliasID = -1;
			pAvatar_regReachDestination.args = pAvatar_regReachDestination_args;

			pAvatarModule.methods["regReachDestination"] = pAvatar_regReachDestination; 
			pAvatarModule.cell_methods["regReachDestination"] = pAvatar_regReachDestination;

			pAvatarModule.idcell_methods[pAvatar_regReachDestination.methodUtype] = pAvatar_regReachDestination;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(regReachDestination / 2).");

			List<DATATYPE_BASE> pAvatar_regSkillResult_args = new List<DATATYPE_BASE>();
			pAvatar_regSkillResult_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_regSkillResult_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_regSkillResult = new Method();
			pAvatar_regSkillResult.name = "regSkillResult";
			pAvatar_regSkillResult.methodUtype = 5;
			pAvatar_regSkillResult.aliasID = -1;
			pAvatar_regSkillResult.args = pAvatar_regSkillResult_args;

			pAvatarModule.methods["regSkillResult"] = pAvatar_regSkillResult; 
			pAvatarModule.cell_methods["regSkillResult"] = pAvatar_regSkillResult;

			pAvatarModule.idcell_methods[pAvatar_regSkillResult.methodUtype] = pAvatar_regSkillResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(regSkillResult / 5).");

			List<DATATYPE_BASE> pAvatar_regUseSkill_args = new List<DATATYPE_BASE>();
			pAvatar_regUseSkill_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_regUseSkill_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_regUseSkill = new Method();
			pAvatar_regUseSkill.name = "regUseSkill";
			pAvatar_regUseSkill.methodUtype = 4;
			pAvatar_regUseSkill.aliasID = -1;
			pAvatar_regUseSkill.args = pAvatar_regUseSkill_args;

			pAvatarModule.methods["regUseSkill"] = pAvatar_regUseSkill; 
			pAvatarModule.cell_methods["regUseSkill"] = pAvatar_regUseSkill;

			pAvatarModule.idcell_methods[pAvatar_regUseSkill.methodUtype] = pAvatar_regUseSkill;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(regUseSkill / 4).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "UINT8";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "ROOM_NUM";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "UINT32";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "INT8";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "MATCH_CODE";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PYTHON";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 20;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "DIRECTION3D";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}