/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Room.def
	public class EntityBaseEntityCall_RoomBase : EntityCall
	{

		public EntityBaseEntityCall_RoomBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_RoomBase : EntityCall
	{

		public EntityCellEntityCall_RoomBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void enterGameWorld(byte[] arg1, Vector3 arg2, Vector3 arg3)
		{
			Bundle pBundle = newCall("enterGameWorld", 0);
			if(pBundle == null)
				return;

			bundle.writeEntitycall(arg1);
			bundle.writeVector3(arg2);
			bundle.writeVector3(arg3);
			sendCall(null);
		}

	}
	}

