/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avatar.def
	public class EntityBaseEntityCall_AvatarBase : EntityCall
	{

		public EntityBaseEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void startMatching(Int32 arg1, Int32 arg2, Int32 arg3)
		{
			Bundle pBundle = newCall("startMatching", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			bundle.writeInt32(arg2);
			bundle.writeInt32(arg3);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AvatarBase : EntityCall
	{

		public EntityCellEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void getProps(Int32 arg1)
		{
			Bundle pBundle = newCall("getProps", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

		public void reachDestination()
		{
			Bundle pBundle = newCall("reachDestination", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void regProgress(Int32 arg1)
		{
			Bundle pBundle = newCall("regProgress", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

		public void skillResult(Int32 arg1, Int32 arg2)
		{
			Bundle pBundle = newCall("skillResult", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			bundle.writeInt32(arg2);
			sendCall(null);
		}

		public void useSkill(Int32 arg1, Int32 arg2)
		{
			Bundle pBundle = newCall("useSkill", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			bundle.writeInt32(arg2);
			sendCall(null);
		}

	}
	}
